### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by denver-s** [octo-technology/tezos-academy#11]
Chapter 1:
- develloped

Chapter 4:
- decinmals
- Substraction

Chapter 7:
- Don't forget the _attribAtes_

Chapter 8:
- Change the last _parameterS_ (should be singular)

**Comment by AymericBethencourt** [comment]
Thanks for the pull request, it has been merged :)

**Comment by denver-s** [comment]
https://www.reddit.com/r/tezos/comments/jzapjp/just_got_an_ad_for_tezosacademy_dot_io_on_brave/

I think you guys should do an extensive check of the mispelled words.

**Comment by denver-s** [comment]
For example:

https://github.com/octo-technology/tezos-academy/blob/00fcf6c6395e4cc8f36d11302950555e080ca89b/src/frontend/src/pages/ChapterAbout/ChapterAbout.data.tsx#L3

`We are throwing everything we’ve got at them, that means even you rookie,` should be "even if you are a rookie"?
